[package]
name = "leptos-example"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.15", features = ["csr"] }
leptos_router = "0.8.11"
gloo-net = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
